name: Nexus Heartbeat

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Nexus Server
        run: curl -X POST https://nexus-response.onrender.com/webhook
